import sys
sys.path += ['../../utils/']
from utils import TreeNode, Test

def tests(solution):
    t1 = TreeNode.build_tree([1,3],0)
    t2 = TreeNode.build_tree([1,2],0)
    r = TreeNode.build_tree([2,5],0)
    assert TreeNode.isSameTree(solution(t1, t2),r)
    t1 = TreeNode.build_tree([1],0)
    t2 = TreeNode.build_tree([1,2,3],0)
    r = TreeNode.build_tree([2,2,3],0)
    assert TreeNode.isSameTree(solution(t1, t2),r)
    t1 = TreeNode.build_tree([1,3],0)
    t2 = TreeNode.build_tree([1,2,3],0)
    r = TreeNode.build_tree([2,5,3],0)
    assert TreeNode.isSameTree(solution(t1, t2),r)
    t1 = TreeNode.build_tree([1,3,5],0)
    t2 = TreeNode.build_tree([1,2,3],0)
    r = TreeNode.build_tree([2,5,8],0)
    assert TreeNode.isSameTree(solution(t1, t2),r)
    t1 = TreeNode.build_tree([1,3,5,None,None,8,7],0)
    t2 = TreeNode.build_tree([1,2,3],0)
    r = TreeNode.build_tree([2,5,8,None,None,8,7],0)
    assert TreeNode.isSameTree(solution(t1, t2),r)
    t1 = TreeNode.build_tree([1,2,None,3,None,None,None,4],0)
    t2 = TreeNode.build_tree([2,None,4,None,None,None,6,None,None,None,None,None,None,None,8],0)
    r = TreeNode.build_tree([3,2,4,3,None,None,6,4,None,None,None,None,None,None,8],0)
    assert TreeNode.isSameTree(solution(t1, t2),r)
    t1 = TreeNode.build_tree([1,3,5,3,None,8,7],0)
    t2 = TreeNode.build_tree([1,2,3,None,None,2,3],0)
    r = TreeNode.build_tree([2,5,8,3,None,10,10],0)
    assert TreeNode.isSameTree(solution(t1, t2),r)
    t1 = TreeNode.build_tree([1,3,5,None,5,8,7],0)
    t2 = TreeNode.build_tree([1,2,3,2,None,1,3],0)
    r = TreeNode.build_tree([2,5,8,2,5,9,10],0)
    assert TreeNode.isSameTree(solution(t1, t2),r)
    t1 = TreeNode.build_tree([3,2,1,None,5,None,3],0)
    t2 = TreeNode.build_tree([2,1,3,None,4,None,7],0)
    r = TreeNode.build_tree([5,3,4,None,9,None,10],0)
    assert TreeNode.isSameTree(solution(t1, t2),r)

def advanced_tests(solution):
    Test.template(tests, solution)
